# permissions for end users to view podlisters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlister-viewer-role
rules:
- apiGroups:
  - pod-lister.example.com
  resources:
  - podlisters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pod-lister.example.com
  resources:
  - podlisters/status
  verbs:
  - get
