# permissions for end users to edit podlisters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlister-editor-role
rules:
- apiGroups:
  - pod-lister.example.com
  resources:
  - podlisters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pod-lister.example.com
  resources:
  - podlisters/status
  verbs:
  - get
